title: "مدونة عمر"
baseurl: ""
url: "https://omarhmza.github.io"
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

# إعدادات اللغة والاتجاه
locale: "ar-SA"
rtl: true
words_per_minute: 150

# تفعيل القائمة العلوية
navigation: main 

# إعدادات الروابط للعربية
slugify:
  mode: "pretty"

# نظام الأقسام والوسوم
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# الإعدادات الافتراضية للمقالات
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
