# إعدادات الموقع
url: "https://omrhmza.github.io"
baseurl: "" 
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"
title: "عمر حمزة"
subtitle: "الشاعر الجديد"

# إعدادات البحث واللغة
search: true
search_full_content: true

# ربط ملف اللغة (تأكد أن اسم الملف داخل مجلد _data هو ui-text.yml)
data:
  ui_text: "ui-text"

# الإضافات
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# إعدادات الترقيم التسلسلي (Pagination)
paginate: 10
paginate_path: "/page:num/"

# إعدادات الكاتب
author:
  name: " عمر حمزة"
  avatar: "/assets/images/morgan-custom.jpg"
  bio: "أنا شاب سوري أدرس اللغة الإنكليزية...مهتم بالأدب بشكل عام...و الشعر العربي العمودي بشكل خاص..."
  location: "الجمهورية العربية السورية"
  links:
    - label: "تويتر"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/omrhmza"

# تعليقات Giscus
comments:
  provider: "custom"

# إعدادات مسار التنقل (الخبز)
breadcrumbs: true

# الإعدادات الافتراضية (هنا تفعيل الأوسمة واللغة لكل مقال)
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      comments: true
      share: true
      related: true
      show_date: true
      read_time: true      
      words_per_minute: 150
      breadcrumbs: true    
      taxonomy: true       # تفعيل عرض الأوسمة والتصنيفات في نهاية المقال
      toc: false           
      entries_layout: grid 

# إعدادات الروابط الدائمة
permalink: /:categories/:title/
