# إعدادات الموقع
url: "https://omrhmza.github.io"
baseurl: "" # اتركه فارغاً هكذا
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"
locale: "ar-SA"
title: "مدونة عمر"
subtitle: "واحة الشعر والأدب"

# الإضافات (حل مشكلة الايرور)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# إعدادات الكاتب
author:
  name: "عمر"
  bio: "مهتم بالشعر والأدب العربي"
  location: "المملكة العربية السعودية"
  links:
    - label: "تويتر"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/omrhmza"

# تعليقات Giscus
comments:
  provider: "giscus"
  giscus:
    repo: "omrhmza/omrhmza.github.io"
    repo_id: "R_kgDOQxw4AQ"
    category: "Announcements"
    category_id: "DIC_kwDOQxw4Ac4C0cGj"
    mapping: "pathname"
    strict: "0"
    reactions_enabled: "1"
    input_position: "bottom"
    theme: "dark"
    lang: "ar"

# الإعدادات الافتراضية
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      comments: true
      share: true
      related: true
      show_date: true
