title: "مدونة عمر"
baseurl: "/blog"
url: "https://omarhmza.github.io"
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
  # تفعيل نظام الأقسام والتاغات
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# إعدادات افتراضية لعرض المقالات (ضروري جداً)
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      share: true
      
  locale: "ar-SA"
rtl: true

# تفعيل القائمة العلوية التي أنشأناها
navigation: main 
words_per_minute: 150
# إعدادات الروابط للعربية
slugify:
  mode: "pretty"

